package main

// configwriter — called silently by both the Windows (Inno Setup) and macOS
// (postinstall) installers after the user completes the wizard.
//
// It receives all user-supplied values as CLI flags and writes them to the
// appsettings.json (for .NET) and .env (for the Go service) files inside the
// install directory.

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

// ── CLI flags ─────────────────────────────────────────────────────────────────

var (
	installDir = flag.String("installdir", "", "Root installation directory (required)")

	// Database
	dbHost = flag.String("dbhost", "localhost", "PostgreSQL host")
	dbPort = flag.String("dbport", "5432", "PostgreSQL port")
	dbName = flag.String("dbname", "genreport", "PostgreSQL database name")
	dbUser = flag.String("dbuser", "postgres", "PostgreSQL username")
	dbPass = flag.String("dbpassword", "", "PostgreSQL password")

	// Ports
	dotnetPort   = flag.String("dotnetport", "5000", ".NET API port")
	goPort       = flag.String("goport", "12334", "Go service port")
	rabbitmqPort = flag.String("rabbitmqport", "5672", "RabbitMQ AMQP port")
	ollamaPort   = flag.String("ollamaport", "11434", "Ollama port")

	// SMTP
	smtpHost = flag.String("smtphost", "", "SMTP host")
	smtpPort = flag.String("smtpport", "587", "SMTP port")
	smtpUser = flag.String("smtpuser", "", "SMTP username")
	smtpPass = flag.String("smtppass", "", "SMTP password")
	smtpFrom = flag.String("smtpfrom", "noreply@genreport.app", "SMTP from address")

	// Cloudflare R2
	r2AccountID = flag.String("r2accountid", "", "R2 Account ID")
	r2Bucket    = flag.String("r2bucket", "", "R2 Bucket name")
	r2AccessKey = flag.String("r2accesskey", "", "R2 Access Key ID")
	r2SecretKey = flag.String("r2secretkey", "", "R2 Secret Access Key")
	r2PublicURL = flag.String("r2publicurl", "", "R2 Public URL")
)

func main() {
	flag.Parse()

	if *installDir == "" {
		fmt.Fprintln(os.Stderr, "error: --installdir is required")
		os.Exit(1)
	}

	if err := writeAppSettings(*installDir); err != nil {
		log.Fatalf("failed to write appsettings.json: %v", err)
	}

	if err := writeDotEnv(*installDir); err != nil {
		log.Fatalf("failed to write .env: %v", err)
	}

	fmt.Println("Genreport configuration written successfully.")
}

// ── appsettings.json (.NET) ───────────────────────────────────────────────────

const appSettingsTemplate = `{
  "ConnectionStrings": {
    "DefaultConnection": "Host={{.DBHost}};Port={{.DBPort}};Database={{.DBName}};Username={{.DBUser}};Password={{.DBPass}}"
  },
  "AppSettings": {
    "DotNetPort": "{{.DotnetPort}}",
    "GoServiceUrl": "http://localhost:{{.GoPort}}"
  },
  "Smtp": {
    "Host":     "{{.SmtpHost}}",
    "Port":     {{.SmtpPort}},
    "Username": "{{.SmtpUser}}",
    "Password": "{{.SmtpPass}}",
    "From":     "{{.SmtpFrom}}"
  },
  "R2": {
    "AccountId":  "{{.R2AccountID}}",
    "Bucket":     "{{.R2Bucket}}",
    "AccessKey":  "{{.R2AccessKey}}",
    "SecretKey":  "{{.R2SecretKey}}",
    "PublicUrl":  "{{.R2PublicURL}}"
  }
}
`

func writeAppSettings(dir string) error {
	tpl, err := template.New("appsettings").Parse(appSettingsTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "dotnet", "appsettings.Production.json")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, configData())
}

// ── .env (Go service) ─────────────────────────────────────────────────────────

const dotEnvTemplate = `# Auto-generated by Genreport installer — do not edit manually.
DB_HOST={{.DBHost}}
DB_PORT={{.DBPort}}
DB_NAME={{.DBName}}
DB_USER={{.DBUser}}
DB_PASSWORD={{.DBPass}}

PORT={{.GoPort}}
DOTNET_URL=http://localhost:{{.DotnetPort}}
RABBITMQ_URL=amqp://guest:guest@localhost:{{.RabbitMQPort}}/
OLLAMA_URL=http://localhost:{{.OllamaPort}}

SMTP_HOST={{.SmtpHost}}
SMTP_PORT={{.SmtpPort}}
SMTP_USER={{.SmtpUser}}
SMTP_PASS={{.SmtpPass}}
SMTP_FROM={{.SmtpFrom}}

R2_ACCOUNT_ID={{.R2AccountID}}
R2_BUCKET={{.R2Bucket}}
R2_ACCESS_KEY={{.R2AccessKey}}
R2_SECRET_KEY={{.R2SecretKey}}
R2_PUBLIC_URL={{.R2PublicURL}}
`

func writeDotEnv(dir string) error {
	tpl, err := template.New("dotenv").Parse(dotEnvTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "go", ".env")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, configData())
}

// ── Data bag ──────────────────────────────────────────────────────────────────

type Config struct {
	DBHost, DBPort, DBName, DBUser, DBPass string
	DotnetPort, GoPort                     string
	RabbitMQPort, OllamaPort              string
	SmtpHost, SmtpPort, SmtpUser          string
	SmtpPass, SmtpFrom                    string
	R2AccountID, R2Bucket                 string
	R2AccessKey, R2SecretKey, R2PublicURL string
}

func configData() Config {
	return Config{
		DBHost: *dbHost, DBPort: *dbPort, DBName: *dbName,
		DBUser: *dbUser, DBPass: *dbPass,
		DotnetPort: *dotnetPort, GoPort: *goPort,
		RabbitMQPort: *rabbitmqPort, OllamaPort: *ollamaPort,
		SmtpHost: *smtpHost, SmtpPort: *smtpPort, SmtpUser: *smtpUser,
		SmtpPass: *smtpPass, SmtpFrom: *smtpFrom,
		R2AccountID: *r2AccountID, R2Bucket: *r2Bucket,
		R2AccessKey: *r2AccessKey, R2SecretKey: *r2SecretKey, R2PublicURL: *r2PublicURL,
	}
}
