package main

// configwriter — called silently by both the Windows (Inno Setup) and macOS
// (postinstall) installers after the user completes the wizard.
//
// It receives all user-supplied values as CLI flags and writes:
//   - {install_dir}/genreport.conf          — read by the launcher (APP_PORT)
//   - {install_dir}/dotnet/appsettings.Production.json  — .NET API config
//   - {install_dir}/go/.env                             — Go service config
//
// Internal service ports are HARDCODED here and in the launcher; they are
// never surfaced to the user.

import (
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

// ── Internal ports (match constants in launcher/main.go) ─────────────────────
const (
	internalDotnetPort   = "5001"
	internalGoPort       = "12334"
	internalRabbitMQPort = "5672"
	internalOllamaPort   = "11434"
)

// ── CLI flags ─────────────────────────────────────────────────────────────────
var (
	installDir = flag.String("installdir", "", "Root installation directory (required)")
	appPort    = flag.String("appport", "2905", "Public-facing application port")

	// Database
	dbHost = flag.String("dbhost", "localhost", "PostgreSQL host")
	dbPort = flag.String("dbport", "5432", "PostgreSQL port")
	dbName = flag.String("dbname", "genreport", "PostgreSQL database name")
	dbUser = flag.String("dbuser", "postgres", "PostgreSQL username")
	dbPass = flag.String("dbpassword", "", "PostgreSQL password")

	// SMTP
	smtpHost = flag.String("smtphost", "", "SMTP host")
	smtpPort = flag.String("smtpport", "587", "SMTP port")
	smtpUser = flag.String("smtpuser", "", "SMTP username")
	smtpPass = flag.String("smtppass", "", "SMTP password")
	smtpFrom = flag.String("smtpfrom", "noreply@genreport.app", "SMTP from address")

	// Cloudflare R2
	r2AccountID = flag.String("r2accountid", "", "R2 Account ID")
	r2Bucket    = flag.String("r2bucket", "", "R2 Bucket name")
	r2AccessKey = flag.String("r2accesskey", "", "R2 Access Key ID")
	r2SecretKey = flag.String("r2secretkey", "", "R2 Secret Access Key")
	r2PublicURL = flag.String("r2publicurl", "", "R2 Public URL")

	// Security — auto-generated if empty
	jwtSecret     = flag.String("jwtsecret", "", "JWT signing secret (auto-generated if blank)")
	encryptionKey = flag.String("encryptionkey", "", "AES encryption master key (auto-generated if blank)")
)

// generateSecret returns a cryptographically-random hex string of the given byte length.
// byteLen=32 → 64 hex chars (256-bit key).
func generateSecret(byteLen int) string {
	b := make([]byte, byteLen)
	if _, err := rand.Read(b); err != nil {
		log.Fatalf("failed to generate random secret: %v", err)
	}
	return hex.EncodeToString(b)
}

func main() {
	flag.Parse()

	if *installDir == "" {
		fmt.Fprintln(os.Stderr, "error: --installdir is required")
		os.Exit(1)
	}

	// Auto-generate secrets if the caller did not supply them.
	if *jwtSecret == "" {
		s := generateSecret(32) // 256-bit
		jwtSecret = &s
		fmt.Println("JWT secret auto-generated.")
	}
	if *encryptionKey == "" {
		s := generateSecret(32) // 256-bit
		encryptionKey = &s
		fmt.Println("Encryption master key auto-generated.")
	}

	if err := writeLauncherConf(*installDir); err != nil {
		log.Fatalf("failed to write genreport.conf: %v", err)
	}

	if err := writeAppSettings(*installDir); err != nil {
		log.Fatalf("failed to write appsettings.json: %v", err)
	}

	if err := writeDotEnv(*installDir); err != nil {
		log.Fatalf("failed to write .env: %v", err)
	}

	fmt.Printf("Genreport configuration written. Application will be available at http://localhost:%s\n", *appPort)
}

// ── genreport.conf (read by launcher) ────────────────────────────────────────

const launcherConfTemplate = `# Genreport launcher configuration
# Auto-generated by installer — edit with care.
APP_PORT={{.AppPort}}
`

func writeLauncherConf(dir string) error {
	tpl, err := template.New("launcherconf").Parse(launcherConfTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "genreport.conf")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, configData())
}

// ── appsettings.json (.NET) ───────────────────────────────────────────────────
// The .NET API always listens on internalDotnetPort — the launcher sets
// ASPNETCORE_URLS at process start time. No port value is needed here.

const appSettingsTemplate = `{
  "ConnectionStrings": {
    "DefaultConnection": "Host={{.DBHost}};Port={{.DBPort}};Database={{.DBName}};Username={{.DBUser}};Password={{.DBPass}}"
  },
  "AppSettings": {
    "GoServiceUrl": "http://localhost:{{.InternalGoPort}}",
    "JwtSecret": "{{.JwtSecret}}",
    "EncryptionKey": "{{.EncryptionKey}}",
    "CreateDb": true,
    "DeleteDb": true
  },
  "Smtp": {
    "Host":     "{{.SmtpHost}}",
    "Port":     {{.SmtpPort}},
    "Username": "{{.SmtpUser}}",
    "Password": "{{.SmtpPass}}",
    "From":     "{{.SmtpFrom}}"
  },
  "R2": {
    "AccountId": "{{.R2AccountID}}",
    "Bucket":    "{{.R2Bucket}}",
    "AccessKey": "{{.R2AccessKey}}",
    "SecretKey": "{{.R2SecretKey}}",
    "PublicUrl": "{{.R2PublicURL}}"
  }
}
`

func writeAppSettings(dir string) error {
	tpl, err := template.New("appsettings").Parse(appSettingsTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "dotnet", "appsettings.Production.json")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, configData())
}

// ── .env (Go service) ─────────────────────────────────────────────────────────
// Internal ports are hardcoded — the Go service always binds to internalGoPort.

const dotEnvTemplate = `# Auto-generated by Genreport installer — do not edit manually.
DB_HOST={{.DBHost}}
DB_PORT={{.DBPort}}
DB_NAME={{.DBName}}
DB_USER={{.DBUser}}
DB_PASSWORD={{.DBPass}}

CREATE_DB=true
DELETE_DB=true

PORT={{.InternalGoPort}}
DOTNET_URL=http://localhost:{{.InternalDotnetPort}}
RABBITMQ_URL=amqp://guest:guest@localhost:{{.InternalRabbitMQPort}}/
OLLAMA_URL=http://localhost:{{.InternalOllamaPort}}

JWT_SECRET={{.JwtSecret}}
ENCRYPTION_KEY={{.EncryptionKey}}

SMTP_HOST={{.SmtpHost}}
SMTP_PORT={{.SmtpPort}}
SMTP_USER={{.SmtpUser}}
SMTP_PASS={{.SmtpPass}}
SMTP_FROM={{.SmtpFrom}}

R2_ACCOUNT_ID={{.R2AccountID}}
R2_BUCKET={{.R2Bucket}}
R2_ACCESS_KEY={{.R2AccessKey}}
R2_SECRET_KEY={{.R2SecretKey}}
R2_PUBLIC_URL={{.R2PublicURL}}
`

func writeDotEnv(dir string) error {
	tpl, err := template.New("dotenv").Parse(dotEnvTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "go", ".env")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, configData())
}

// ── Data bag ──────────────────────────────────────────────────────────────────

type Config struct {
	// User-supplied
	AppPort                          string
	DBHost, DBPort, DBName           string
	DBUser, DBPass                   string
	SmtpHost, SmtpPort, SmtpUser     string
	SmtpPass, SmtpFrom               string
	R2AccountID, R2Bucket            string
	R2AccessKey, R2SecretKey         string
	R2PublicURL                      string
	// Security (auto-generated or user-supplied)
	JwtSecret     string
	EncryptionKey string
	// Hardcoded internal
	InternalDotnetPort, InternalGoPort       string
	InternalRabbitMQPort, InternalOllamaPort string
}

func configData() Config {
	return Config{
		AppPort: *appPort,
		DBHost:  *dbHost, DBPort: *dbPort, DBName: *dbName,
		DBUser: *dbUser, DBPass: *dbPass,
		SmtpHost: *smtpHost, SmtpPort: *smtpPort, SmtpUser: *smtpUser,
		SmtpPass: *smtpPass, SmtpFrom: *smtpFrom,
		R2AccountID: *r2AccountID, R2Bucket: *r2Bucket,
		R2AccessKey: *r2AccessKey, R2SecretKey: *r2SecretKey, R2PublicURL: *r2PublicURL,
		JwtSecret:     *jwtSecret,
		EncryptionKey: *encryptionKey,
		InternalDotnetPort:   internalDotnetPort,
		InternalGoPort:       internalGoPort,
		InternalRabbitMQPort: internalRabbitMQPort,
		InternalOllamaPort:   internalOllamaPort,
	}
}
